const TodoActionTypes = {
    ADD_TODO_START: 'ADD_TODO_START',
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',

    TOGGLE_TODO_COMPLETION_START: 'TOGGLE_TODO_COMPLETION_START',
    TOGGLE_TODO_COMPLETION_SUCCESS: 'TOGGLE_TODO_COMPLETION_SUCCESS',
    TOGGLE_TODO_COMPLETION_FAILURE: 'TOGGLE_TODO_COMPLETION_FAILURE',

    DELETE_TODO_START: 'DELETE_TODO_START',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',

    CLEAR_COMPLETED_START: 'CLEAR_COMPLETED_START',
    CLEAR_COMPLETED_SUCCESS: 'CLEAR_COMPLETED_SUCCESS',
    CLEAR_COMPLETED_FAILURE: 'CLEAR_COMPLETED_FAILURE',

};

export default TodoActionTypes;
