const UserActionTypes = {
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  NO_USER_DETECETD: 'NO_USER_DETECETD',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  USER_UNAUTHORISED: 'USER_UNAUTHORISED',

  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
};

export default UserActionTypes;
