---
name: Build and Push Node image to Google Cloud Platform

on:
  push:
    branches: [development]

jobs:
  build-push-gcr:
    permissions:
      contents: "read"
      id-token: "write"

    name: Build and Push to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          username: "oauth2accesstoken"
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ secrets.GAR_LOCATION_DEV }}-docker.pkg.dev'

      - name: Build Docker Image
        run: docker build . -t '${{ secrets.IMAGE_NAME_DEV }}:latest' --build-arg GCP_ENV=development

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: '${{steps.increment-git-tag.outputs.git-tag}}'
        run: |-
          docker tag '${{ secrets.IMAGE_NAME_DEV }}:latest' '${{ secrets.GAR_LOCATION_DEV }}-docker.pkg.dev/${{ secrets.PROJECT_ID_DEV }}/images/${{ secrets.IMAGE_NAME_DEV }}:latest'
          docker tag '${{ secrets.IMAGE_NAME_DEV }}:latest' '${{ secrets.GAR_LOCATION_DEV }}-docker.pkg.dev/${{ secrets.PROJECT_ID_DEV }}/images/${{ secrets.IMAGE_NAME_DEV }}:${{ github.sha }}'
          docker push --all-tags '${{ secrets.GAR_LOCATION_DEV }}-docker.pkg.dev/${{ secrets.PROJECT_ID_DEV }}/images/${{ secrets.IMAGE_NAME_DEV }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: '${{ secrets.SERVICE_DEV }}'
          region: '${{ secrets.REGION_DEV }}'
          # NOTE: If using a pre-built image, update the image name here
          image: '${{ secrets.GAR_LOCATION_DEV }}-docker.pkg.dev/${{ secrets.PROJECT_ID_DEV }}/images/${{ secrets.IMAGE_NAME_DEV }}:latest'

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo '${{ steps.deploy.outputs.url }}'
