---
name: Build and Push Node image to Google Cloud Platform
on:
  push:
    branches: [development]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest

    # ENV variables specify variables that can be used through the steps in the workflow
    env:
      IMAGE_NAME: immichaelpepper/todo-app-development-image
      PROJECT_ID: todo-app-development-356018
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{secrets.SERVICE_ACCOUNT_KEY}}
          project_id: ${{env.PROJECT_ID}}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build . -t $IMAGE_NAME:latest 

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry 
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest europe-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest europe-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push europe-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
          docker push europe-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG